PR to merge Feature into develop
UmairAhmad125/private-events pull request #1
Opened 2020-09-18 14:19 UTC by UmairAhmad125

In this project(private events), 
- We build associations like one-to-one, one-to-many, and many-to-many. 
- Added validations 
- More details are mentioned in the readme file

2020-09-18 17:17 UTC, Ispirett requested changes
## Status Changes required
Really great work with this project @UmairAhmad125  @talhawaqar  your ui looks lovely 👍 
 
Below are some missing features to implement.

- [ ] There currently is no way to invite a user to an event.
User as an Event attendee ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/attendee_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2020-09-20 13:31 UTC, UmairAhmad125 commented
> ## Status Changes required
> Really great work with this project @UmairAhmad125 @talhawaqar your ui looks lovely 
> 
> Below are some missing features to implement.
> 
> * [ ]  There currently is no way to invite a user to an event.
>   User as an Event attendee ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/attendee_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

All the required associations are there
Invite a user is an [extra credit](https://ibb.co/6RnM27h) task

2020-09-20 16:38 UTC, mosesogwo approved these changes
**Hello:wave: Well done on this:clap: Your project is approved**

 Please check your specs. You have one failing test.

### Status: Approved :heavy_check_mark:

2020-09-20 16:38 UTC, mosesogwo commented on README.md
> +- Github: [@talhawaqar](https://github.com/talhawaqar)
Check the appearance of this section of your README.

2020-09-21 08:03 UTC, merged